POST http://localhost:3000/cards
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: 634acfe1f470f96c0c324948

{
    "name":"Нет вобле4!",
    "link":"https://memepedia.ru/wp-content/uploads/2022/10/ffaq1d_xkaez4n--768x511.jpg"
}

###

GET http://localhost:3000/cards
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

### Лайк

PUT http://localhost:3000/cards/635a379609ad85169d801f95/likes
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: 634acfe1f470f96c0c324948

### Дизлайк

DELETE http://localhost:3000/cards/635a379609ad85169d801f95/likes
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: 634acfe1f470f96c0c324948

###

### !!! Удаление карточки

DELETE http://localhost:3000/cards/6359aeb68f1c35f6f74e5729
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: 634acfe1f470f96c0c324948

###
