POST http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name":"Тестовый пользователь",
  "about":"где-то работает",
  "avatar":"https://memepedia.ru/wp-content/uploads/2022/10/ffaq1d_xkaez4n--768x511.jpg"
}

###

GET http://localhost:3000/users
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

PATCH http://localhost:3000/users/me
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "name":"Пользователь",
  "about":"работает"
}

###
PATCH http://localhost:3000/users/me/avatar
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "avatar":"http://avatars.lend"
}

###
